name = "bazaar_trader"
version = "0.0.1"

description = ""
# licences = ["Apache-2.0"]
repository = { type = "github", user = "Clearbloo", repo = "BazaarTrader" }
dependencies = { gleam_stdlib = ">= 0.50.0 and < 1.0.0" , math = ">= 0.7.0 and < 1.0.0" , gleam_community_maths = ">= 1.1.1 and < 2.0.0" }
dev-dependencies = { gleeunit = ">= 1.3.0 and < 2.0.0" }
# links = [{ title = "Website", href = "" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
