name = "bazaar_trader"
version = "0.0.1"

description = ""
repository = { type = "github", user = "Clearbloo", repo = "BazaarTrader" }
gleam = ">= 1.10.0"

[dependencies]
gleam_stdlib = ">= 0.50.0 and < 1.0.0"
math = ">= 0.7.0 and < 1.0.0" 
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleeunit = ">= 1.3.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
squirrel = ">= 4.6.0 and < 5.0.0" # Generates sql functions
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]


# links = [{ title = "Website", href = "" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
